name: "Install"
description: "Installs the ci-build tools."
inputs:
  install_dir:
    description: "Installation directory."
    default: "/opt/ci-fuzz"
    required: false
runs:
  using: "docker"
  image: "docker://cifuzz/cictl:2.18.1"
  entrypoint: "cp"
  args: ["/usr/bin/start_fuzzing.sh", "/github/workspace/"]
