name: "Install"
description: "Installs the ci-build tools."
inputs:
  install_dir:
    description: "Installation directory."
    default: "/opt/ci-fuzz"
    required: false
runs:
  using: "docker"
  image: "docker://cifuzz/builder:ci-build"
  entrypoint: "cp"
  args: ["-R", "/opt/ci-fuzz", "/github/workspace/"]
